# Generated by Django 4.1 on 2023-06-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=1, max_length=64, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
